#include "toGLEnum.h"

namespace render
{

toGLMinFilter[TMF_NEAREST] = GL_NEAREST;
toGLMinFilter[TMF_LINEAR] = GL_LINEAR;
toGLMinFilter[TMF_NEAREST_MIPMAP_NEAREST] = GL_NEAREST_MIPMAP_NEAREST;
toGLMinFilter[TMF_LINEAR_MIPMAP_NEAREST] = GL_LINEAR_MIPMAP_NEAREST;
toGLMinFilter[TMF_NEAREST_MIPMAP_LINEAR] = GL_NEAREST_MIPMAP_LINEAR;
toGLMinFilter[TMF_LINEAR_MIPMAP_LINEAR] = GL_LINEAR_MIPMAP_LINEAR;
	
toGLMagFilter[TMAGF_NEAREST] = GL_NEAREST;
toGLMagFilter[TMAGF_LINEAR] = GL_LINEAR;
	
toGLWrap[TW_REPEAT] = GL_REPEAT;
toGLWrap[TW_CLAMP_TO_EDGE] = GL_CLAMP_TO_EDGE;
toGLWrap[TW_CLAMP_TO_BORDER] = GL_CLAMP_TO_BORDER;
toGLWrap[TW_MIRRORED_REPEAT] = GL_MIRRORED_REPEAT;
toGLWrap[TW_MIRROR_CLAMP_TO_EDGE] = GL_MIRROR_CLAMP_TO_EDGE;

}
