#include "Texture2D.h"
#include "VideoDriver.h"
#include "GLSpecificInfo.h"
#include "Logger.h"

namespace render
{

Texture2D::Texture2D(
	video::VideoDriver *driver, const std::string &name,
	const core::dimension2du &size, ECOLOR_FORMAT format, u8 msaa_n)
    : ITexture(driver, name, size, format), msaa(msaa_n)
{
	texSettings.isRenderTarget = true;

	copyCache = driver->getTextureCreationFlag(ETCF_ALLOW_MEMORY_COPY);

	if (originalColorFormat == ECF_UNKNOWN)
		colorFormat = getBestColorFormat(driver->getColorFormat());

	pitch = size.Width * IImage::getBitsPerPixelFromFormat(colorFormat) / 8;

	// On GLES 3.0 we must use sized internal formats for textures when calling
	// glTexStorage. But ECF_A8R8G8B8 might be mapped to GL_BGRA (an unsized format).
	// Since we don't upload to RTT we can safely pick a different combo that works.
	//if (InternalFormat == GL_BGRA && Driver->getVersion().Major >= 3) {
	//	InternalFormat = GL_RGBA8;
	//	PixelFormat = GL_RGBA;
	//}

	initTexture(nullptr);
}

Texture2D::Texture2D(
	video::VideoDriver *driver, const std::string &name,
	IImage *image, const TextureSettings &settings)
	: Texture(driver, name, image->getSize(), image->getColorFormat(), settings)
{
	texSettings.hasMipMaps = driver->getTextureCreationFlag(ETCF_CREATE_MIP_MAPS) || texSettings.hasMipMaps;
	copyCache = driver->getTextureCreationFlag(ETCF_ALLOW_MEMORY_COPY);

	getParametersFromImage(image);

	if (copyCache || originalSize != size || originalColorFormat != colorFormat) {
		auto copyImage = driver->createImage(colorFormat, size);

		if (image->getDimension() == size)
			image->copyTo(copyImage);
		else
			image->copyToScaling(copyImage);

		image = copyImage;
		imgCache = image;
	}

	initTexture(image);
}

void Texture2D::initTexture(IImage *image)
{
	glGenTextures(1, &texID);
	driver->testGLError();

	bind();

	auto formatInfo = GLSpecificInfo::TextureFormats[format];

	if (texSettings.isRenderTarget) {
		// An INVALID_ENUM error is generated by TexParameter* if target is either
		// TEXTURE_2D_MULTISAMPLE or TEXTURE_2D_MULTISAMPLE_ARRAY, and pname is any
		// sampler state from table 23.18.
		// ~ https://registry.khronos.org/OpenGL/specs/gl/glspec46.core.pdf
		if (msaa == 0) {
			glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
			glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
			glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
			glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);

      texSettings.minF = ETMINF_NEAREST;
			texSettings.wrapU = ETC_CLAMP_TO_EDGE;
			texSettings.wrapV = ETC_CLAMP_TO_EDGE;
		}

		driver->testGLError();
	}
	else {
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);

    texSettings.minF = ETMINF_NEAREST;

		if (texSettings.hasMipMaps) {
			if (driver->getTextureCreationFlag(ETCF_OPTIMIZED_FOR_SPEED))
				glHint(GL_GENERATE_MIPMAP_HINT, GL_FASTEST);
			else if (driver->getTextureCreationFlag(ETCF_OPTIMIZED_FOR_QUALITY))
				glHint(GL_GENERATE_MIPMAP_HINT, GL_NICEST);
			else
				glHint(GL_GENERATE_MIPMAP_HINT, GL_DONT_CARE);
		}
		Driver->testGLError();
	}

	u32 levels = texSettings.maxMipLevel;
	if (texSettings.hasMipMaps && levels == 0)
		levels = core::u32_log2(core::max_(size.Width, size.Height)) + 1;

	// reference: <https://www.khronos.org/opengl/wiki/Texture_Storage>
	bool use_tex_storage = driver->getFeatures().TexStorage;

	// On GLES 3.0 if we don't have a sized format suitable for glTexStorage,
	// just avoid using it. Only affects the extension that provides BGRA.
	//if (InternalFormat == GL_BGRA && Driver->getVersion().Major >= 3)
	//	use_tex_storage = false;

	if (msaa == 0) {
		if (use_tex_storage) {
			glTexStorage2D(GL_TEXTURE_2D, levels, formatInfo.InternalFormat,
				size.Width, size.Height);
		} else {
			glTexImage2D(GL_TEXTURE_2D, 0, formatInfo.InternalFormat,
				size.Width, size.Height, 0, formatInfo.PixelFormat, formatInfo.PixelType, 0);
		}
		driver->testGLError();
	}
	else {
		//GLint max_samples = 0;
		//glGetIntegerv(GL_MAX_SAMPLES, &max_samples);
		//MSAA = core::min_(MSAA, (u8)max_samples);

		// glTexImage2DMultisample is supported by OpenGL 3.2+
		// glTexStorage2DMultisample is supported by OpenGL 4.3+ and OpenGL ES 3.1+
		// so pick the most compatible one
		const bool use_gl_impl = driver->getVersion().Spec != OpenGLSpec::ES;

		if (use_gl_impl)
			glTexImage2DMultisample(GL_TEXTURE_2D_MULTISAMPLE, msaa, formatInfo.InternalFormat,
				size.Width, size.Height, GL_TRUE);
		else
			glTexStorage2DMultisample(GL_TEXTURE_2D_MULTISAMPLE, msaa, formatInfo.InternalFormat,
				size.Width, size.Height, GL_TRUE);
		driver->testGLError();
	}

	if (!texSettings.isRenderTarget) {
		uploadTexture(0, 0, image->getData());

		if (texSettings.hasMipMaps)
			regenerateMipMapLevels();

		if (!copyCache && imgCache) {
			imgCache->drop();
			imgCache = nullptr;
		}
	}

	if (!name.empty())
		driver->GLInfo->ObjectLabel(GL_TEXTURE, texID, name.c_str());

	unbind();
}

void Texture2D::bind()
{
	if (bound)
		return;
	glBindTexture(tex2D(), texID);
	driver->testGLError();

	bound = true;
}

void Texture2D::unbind()
{
	if (!bound)
		return;
	glBindTexture(tex2D(), 0);
	driver->testGLError();

	bound = false;
}

void Texture2D::uploadData(img::Image *img, u8 mipLevel)
{
	uploadSubData(width, height, img, mipLevel);
}

void Texture2D::uploadSubData(u32 x, u32 y, img::Image *img, u8 mipLevel)
{
    v2u pos = img->getClipPos();
    v2u size = img->getClipSize();

    if (imgCache && imgMod) {
        rectu srcRect(pos.X, pos.Y, size.X, size.Y);
        rectu dstRect(x, y, size.X, size.Y);
        imgMod->copyTo(img, imgCache.get(), &srcRect, &dstRect);
    }

    bool converted;
    auto convImg = img::convertImageToRGBA(img, converted);

    auto formatInfo = img::pixelFormatInfo.at(convImg->getFormat());

    bind();
    glTexSubImage2D(GL_TEXTURE_2D, 0, (s32)x, (s32)y, (s32)size.X, (s32)size.Y,
        formatInfo.pixelFormat, formatInfo.pixelType, convImg->getData());
    TEST_GL_ERROR();

    if (converted)
        delete convImg;

    unbind();
}

std::vector<img::Image *> Texture2D::downloadData()
{
    img::Image *cachedImg = nullptr;

    if (!imgCache) {
		img::Image *img = new img::Image(format, width, height);

        auto formatInfo = img::pixelFormatInfo.at(format);
        bind();

        if (format == img::PF_INDEX_RGBA8) {
            formatInfo = img::pixelFormatInfo.at(img::PF_RGBA8);
        }

        u8* tempData = new u8[width * height * formatInfo.size / 8];
        glGetTexImage(tex2D(), 0, formatInfo.pixelFormat, formatInfo.pixelType, tempData);
        TEST_GL_ERROR();

        u32 dataSize = width * height * formatInfo.size / 8;
        memcpy(img->getData(), tempData, dataSize);
        delete[] tempData;

        unbind();

        cachedImg = img;
	}
    else
        cachedImg = imgCache.get();

    return {cachedImg};
}

void Texture2D::regenerateMipMaps()
{
	if (!texSettings.hasMipMaps) {
		g_irrlogger->log("Texture2D::regenerateMipMaps() mip maps are disabled", ELL_ERROR);
		return;
	}

	bind();
	glGenerateMipmap(tex2D());
	driver->testGLError();

	unbind();
}

void Texture2D::updateParameters(const TextureSettings &newTexSettings, bool updateLodBias, bool updateAnisotropy)
{
    bind();
    if (texSettings.wrapU != newTexSettings.wrapU) {
        texSettings.wrapU = newTexSettings.wrapU;
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, toGLWrap.at(texSettings.wrapU));
        TEST_GL_ERROR();
    }
    if (texSettings.wrapV != newTexSettings.wrapV) {
        texSettings.wrapV = newTexSettings.wrapV;
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, toGLWrap.at(texSettings.wrapV));
        TEST_GL_ERROR();
    }
    if (texSettings.minF != newTexSettings.minF) {
        texSettings.minF = newTexSettings.minF;
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, toGLMinFilter.at(texSettings.minF));
        TEST_GL_ERROR();
    }
    if (texSettings.magF != newTexSettings.magF) {
        texSettings.magF = newTexSettings.magF;
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, toGLMagFilter.at(texSettings.magF));
        TEST_GL_ERROR();
    }

    if (updateLodBias && texSettings.lodBias != newTexSettings.lodBias) {
        f32 clampedBias = std::clamp<f32>(newTexSettings.lodBias * 0.125, -texSettings.maxLodBias, texSettings.maxLodBias);
        texSettings.lodBias = clampedBias;
        glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_LOD_BIAS, clampedBias);
        TEST_GL_ERROR();
    }
    if (updateAnisotropy && texSettings.anisotropyFilter != newTexSettings.anisotropyFilter) {
        u8 clampedAnisotropy = std::clamp<u8>(newTexSettings.anisotropyFilter, 1, texSettings.maxAnisotropyFilter);
        texSettings.anisotropyFilter = clampedAnisotropy;
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAX_ANISOTROPY, clampedAnisotropy);
        TEST_GL_ERROR();
    }

    unbind();
}

void Texture2D::resize(u32 newWidth, u32 newHeight, img::ImageModifier *imgMod)
{
    if (newWidth <= width || newHeight <= height) // only increasing is allowed
        return;

    u32 oldTexID = texID;
    texID = 0;

    u32 oldWidth = width;
    u32 oldHeight = height;

    width = newWidth;
    height = newHeight;

    initTexture(nullptr);

    bind();

    u32 srcFBO, dstFBO;

    glGenFramebuffers(1, &srcFBO);
    glGenFramebuffers(1, &dstFBO);

    glBindFramebuffer(GL_READ_FRAMEBUFFER, srcFBO);
    glFramebufferTexture2D(GL_READ_FRAMEBUFFER, GL_COLOR_ATTACHMENT0,
                           tex2D(), oldTexID, 0);

    glBindFramebuffer(GL_DRAW_FRAMEBUFFER, dstFBO);
    glFramebufferTexture2D(GL_DRAW_FRAMEBUFFER, GL_COLOR_ATTACHMENT0,
                           tex2D(), texID, 0);

    glBlitFramebuffer(0, 0, oldWidth, oldHeight,
                      0, 0, oldWidth, oldHeight,
                      GL_COLOR_BUFFER_BIT, GL_NEAREST);

    glDeleteFramebuffers(1, &srcFBO);
    glDeleteFramebuffers(1, &dstFBO);

    glDeleteTextures(1, &oldTexID);

    unbind();
}

Texture2D *Texture2D::copy(const std::string &name)
{
	img::Image *cache = downloadData().at(0);
    std::string texName = name.empty() ? getName() : name;
    return new Texture2D(texName, std::unique_ptr<img::Image>(cache->copy()), texSettings);
}

}
