#pragma once

#include <SDL_log.h>

#define LC_APP SDL_LOG_CATEGORY_APPLICATION
#define LC_ERR SDL_LOG_CATEGORY_ERROR
#define LC_ASS SDL_LOG_CATEGORY_ASSERT
#define LC_SYS SDL_LOG_CATEGORY_SYSTEM
#define LC_AUDIO SDL_LOG_CATEGORY_AUDIO
#define LC_VIDEO SDL_LOG_CATEGORY_VIDEO
#define LC_RENDER SDL_LOG_CATEGORY_RENDER
#define LC_INPUT SDL_LOG_CATEGORY_INPUT
#define LC_TEST SDL_LOG_CATEGORY_TEST
