name: android

on:
  push:
    branches:
      - 'main'
    paths_ignore:
      - '.github/workflows/linux.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
  workflow_dispatch:
    branches:
      - 'main'
    paths_ignore:
      - '.github/workflows/linux.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gettext
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
          distribution: 'temurin'
          java-version: '17'
    - name: Build APKs with Gradle
      # "assemblerelease" is very fast after "bundlerelease".
      run: cd android; ./gradlew assemblerelease
    - name: Save armeabi artifact
      uses: actions/upload-artifact@v4
      with:
        name: irr-armeabi-v7a.apk
        path: android/app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned.apk
    - name: Save arm64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: irr-arm64-v8a.apk
        path: android/app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk
    - name: Save x86 artifact
      uses: actions/upload-artifact@v4
      with:
        name: irr-x86.apk
        path: android/app/build/outputs/apk/release/app-x86-release-unsigned.apk
    - name: Save x86_64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: irr-x86_64.apk
        path: android/app/build/outputs/apk/release/app-x86_64-release-unsigned.apk
