name: build

# build on c/cpp changes or workflow changes
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  linux-gl3:
    # Xvfb test is broken on 20.04 for unknown reasons (not our bug)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install g++ cmake libglew-dev libsdl2-dev libpng-dev libjpeg-dev zlib1g-dev xvfb -qyy

      - name: Build
        run: |
          cmake . -DENABLE_OPENGL3=ON
          make -j$(nproc)

  linux-gles2:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install g++ cmake libglew-dev libsdl2-dev libpng-dev libjpeg-dev zlib1g-dev xvfb -qyy

      - name: Build
        run: |
          cmake . -DENABLE_GLES2=ON
          make -j$(nproc)

  mingw:
    name: "MinGW ${{matrix.config.variant}}${{matrix.config.extras}}"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - {variant: win32, arch: i686}
          - {variant: win64, arch: x86_64}
          - {variant: win32, arch: i686, extras: "-sdl"}
          - {variant: win64, arch: x86_64, extras: "-sdl"}
    steps:
      - uses: actions/checkout@v4
      - name: Install compiler
        run: |
          sudo apt-get update && sudo apt-get install cmake -qyy
          ./scripts/ci-get-mingw.sh

      - name: Build
        run: |
          ./scripts/ci-build-mingw.sh package
        env:
          CC: ${{matrix.config.arch}}-w64-mingw32-clang
          CXX: ${{matrix.config.arch}}-w64-mingw32-clang++
          extras: ${{matrix.config.extras}}

      - uses: actions/upload-artifact@v4
        with:
          name: irrlicht-${{matrix.config.variant}}${{matrix.config.extras}}
          path: ./irrlicht-${{matrix.config.variant}}${{matrix.config.extras}}.zip

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          brew update --auto-update
          brew install cmake glew libpng jpeg sdl2
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - name: Build
        run: |
          cmake . -DCMAKE_FIND_FRAMEWORK=LAST
          make -j$(nproc)

  android:
    name: Android ${{ matrix.arch }}
    runs-on: ubuntu-22.04
    env:
       ndk_version: "r25c"
       ANDROID_NDK: ${{ github.workspace }}/android-ndk
    strategy:
      matrix:
        arch: [armeabi-v7a, arm64-v8a, x86, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo rm -f /var/lib/man-db/auto-update
          sudo apt-get update
          sudo apt-get install -qyy wget unzip zip gcc-multilib make cmake

      - name: Cache NDK
        id: cache-ndk
        uses: actions/cache@v4
        with:
          key: android-ndk-${{ env.ndk_version }}-linux
          path: ${{ env.ANDROID_NDK }}

      - name: Install NDK
        run: |
          wget --progress=bar:force "http://dl.google.com/android/repository/android-ndk-${ndk_version}-linux.zip"
          unzip -q "android-ndk-${ndk_version}-linux.zip"
          rm "android-ndk-${ndk_version}-linux.zip"
          mv "android-ndk-${ndk_version}" "${ANDROID_NDK}"
        if: ${{ steps.cache-ndk.outputs.cache-hit != 'true' }}

      - name: Build
        run: ./scripts/ci-build-android.sh ${{ matrix.arch }}

      #- name: Upload Artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: irrlicht-android-${{ matrix.arch }}
      #    path: ${{ runner.temp }}/pkg/${{ matrix.arch }}
