name: linux

on:
  push:
    branches:
      - 'main'
    paths_ignore:
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
  workflow_dispatch:
    branches:
      - 'main'
    paths_ignore:
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
jobs:
  linux-gl3-plus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install g++ make libpng-dev libjpeg-dev libsdl2-dev libsdl2-image-dev libglew-dev

      - name: Build
        run: |
          cmake . -DRENDERER=OpenGL3+
          make -j$(nproc)

      - uses: actions/upload-artifact@v4
        with:
          name: IrrlichtMt-linux-gl3-plus
          path: ./libIrrlichtMt
  
  linux-gles2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install g++ make libpng-dev libjpeg-dev libsdl2-dev libsdl2-image-dev libglew-dev

      - name: Build
        run: |
          cmake . -DRENDERER=OpenGLES2
          make -j$(nproc)

      - uses: actions/upload-artifact@v3
        with:
          name: IrrlichtMt-linux-gles2
          path: ./IrrlichtMt
