name: linux

on:
  push:
    branches:
      - 'main'
    paths_ignore:
      - '.github/workflows/android.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
  workflow_dispatch:
    branches:
      - 'main'
    paths_ignore:
      - '.github/workflows/linux.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
jobs:
  # Older gcc version (should be close to our minimum supported version)
  gcc_7:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          source ./scripts/install.sh
          install_linux_deps g++-7

      - name: Build
        run: |
          source ./scripts/build.sh
          build_on_linux
        env:
          CC: gcc-7
          CXX: g++-7

  # Current gcc version
  gcc_14:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          source ./scripts/install.sh
          install_linux_deps g++-14 libluajit-5.1-dev

      - name: Build
        run: |
          source ./scripts/build.sh
          build_on_linux
        env:
          CC: gcc-14
          CXX: g++-14

  # Older clang version (should be close to our minimum supported version)
  clang_7:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          source ./scripts/install.sh
          install_linux_deps clang-7 llvm-7

      - name: Build
        run: |
          source ./scripts/build.sh
          build_on_linux
        env:
          CC: clang-7
          CXX: clang++-7
          CMAKE_FLAGS: '-DCMAKE_C_FLAGS="-fsanitize=address" -DCMAKE_CXX_FLAGS="-fsanitize=address"'

  # Current clang version
  clang_18:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          source ./scripts/install.sh
          install_linux_deps clang-18 lldb

      - name: Build
        run: |
          source ./scripts/build.sh
          build_on_linux
        env:
          CC: clang-18
          CXX: clang++-18
