name: macos

on:
  push:
    branches:
      - 'main'
    paths_ignore:
      - '.github/workflows/linux.yml'
      - '.github/workflows/windows.yml'
  workflow_dispatch:
    branches:
      - 'main'
    paths_ignore:
      - '.github/workflows/linux.yml'
      - '.github/workflows/windows.yml'
jobs:
  macos-gl3-plus:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          brew update
          brew install cmake libpng jpeg sdl2 sdl2_image glew

      - name: Build
        run: |
          cmake . -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
          -DCMAKE_FIND_FRAMEWORK=LAST -DRENDERER=OpenGL3+
          make -j$(nproc)

      - uses: actions/upload-artifact@v4
        with:
          name: IrrlichtMt-macos-gl3-plus
          path: ./libIrrlichtMt.dylib
          
  macos-gles2:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          brew update
          brew install cmake libpng jpeg sdl2 sdl2_image glew

      - name: Build
        run: |
          cmake . -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
          -DCMAKE_FIND_FRAMEWORK=LAST -DRENDERER=OpenGLES2
          make -j$(nproc)

      - uses: actions/upload-artifact@v4
        with:
          name: IrrlichtMt-macos-gles2
          path: ./libIrrlichtMt.dylib
