name: macos

on:
  push:
    branches:
      - 'main'
    paths_ignore:
      - '.github/workflows/linux.yml'
      - '.github/workflows/windows.yml'
  workflow_dispatch:
    branches:
      - 'main'
    paths_ignore:
      - '.github/workflows/linux.yml'
      - '.github/workflows/windows.yml'
jobs:
  macos-gl3-plus:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          brew update
          brew install cmake libpng jpeg sdl2 sdl2_image sdl2_ttf glew

      - name: Build
        run: |
          cmake -B . \
                -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
                -DCMAKE_FIND_FRAMEWORK=LAST -DRENDERER=OpenGL3+
          cmake --build . --parallel $(nproc)

      - uses: actions/upload-artifact@v4
        with:
          name: IrrlichtRedo-macos-gl3-plus
          path: /Users/runner/work/irrlicht_redo/irrlicht_redo/src/libIrrlichtRedo.dylib
          
  macos-gles2:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          brew update
          brew install cmake libpng jpeg sdl2 sdl2_image sdl2_ttf glew

      - name: Build
        run: |
          cmake -B . \
                -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
                -DCMAKE_FIND_FRAMEWORK=LAST -DRENDERER=OpenGLES2
          cmake --build . --parallel $(nproc)

      - uses: actions/upload-artifact@v4
        with:
          name: IrrlichtRedo-macos-gles2
          path: /Users/runner/work/irrlicht_redo/irrlicht_redo/src/libIrrlichtRedo.dylib
